version: "2"
services:
  web:
    build: .
    ports:
      - "80:5000"
    links:
      - redis
    networks:
      - "compose-demo"

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - "compose-demo"

  lb:
    image: dockercloud/haproxy
    ports:
      - "80:80"
    networks:
      - "compose-demo"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  compose-demo:
