version: "2"
services:
  web:
    build: .
    ports: 
      - 8080
    links:
      - redis
    networks:
      - compose-demo

  redis:
    image: redis
    ports: 
      - 6379
    networks:
      - compose-demo

  lb:
    image: dockercloud/haproxy:latest
    ports:
      - 80:80
    links:
      - web
    networks:
      - compose-demo
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

networks:
  compose-demo:
